name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    strategy:
      matrix:
        environment: [dev, qa, stg, test, prod]
        workflow: [build, deploy, release]
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
      url: https://${{ matrix.environment }}.notprod.live
    uses: ./.github/workflows/${{ matrix.workflow }}.yml
