name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    strategy:
      matrix:
        environment: [dev, qa, stg, test, prod]
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}
      url: https://${{ matrix.environment }}.notprod.live
    steps:
      - name: deploy
        run: echo ${{ secrets.AWS_ACCOUNT_ID }}
        # ...deployment-specific steps
