name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.notprod.live
    steps:
      - name: deploy
        run: echo ${{ secrets.AWS_ACCOUNT_ID }}
        # ...deployment-specific steps
